apiVersion: apps/v1
kind: Deployment
metadata:
  name: a1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: a1
  template:
    metadata:
      labels:
        app: a1
    spec:
      containers:
      - name: a1
        image: yashhh26/a1:latest
        ports:
        - containerPort: 5002
